name = "ai-generative-fill"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

[[d1_databases]]
binding = "agf-database" # DB 将是你在代码中使用的变量名
database_name = "agf-database"
database_id = "8f5d7892-38a5-4f22-9df3-f8165b6c44a3"